/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package My_Form;

import My_Class.connect;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import jdk.jfr.Timestamp;
/**
 *
 * @author Berliani Risqi
 */
public class NonAnggotaForm extends javax.swing.JFrame {

    /**
     * Creates new form NonAnggotaForm
     */
    public NonAnggotaForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupJK = new javax.swing.ButtonGroup();
        buttonGroupPddkn = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        cari = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        field_nama1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTextFieldAlamat1 = new javax.swing.JTextField();
        jRadioButtonSMP1 = new javax.swing.JRadioButton();
        jRadioButtonSMA1 = new javax.swing.JRadioButton();
        jRadioButtonMHS1 = new javax.swing.JRadioButton();
        jRadioButtonKRJ1 = new javax.swing.JRadioButton();
        jRadioButtonMU1 = new javax.swing.JRadioButton();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jRadioButtonPerempuan1 = new javax.swing.JRadioButton();
        jRadioButtonLaki1 = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel3.setBackground(new java.awt.Color(0, 153, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_Images/librarylogin1.png"))); // NOI18N
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 120, -1, -1));

        jLabel2.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Selamat Datang");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 50, -1, -1));

        jButton1.setText("Non Anggota");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        jButton2.setText("Anggota");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 380, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 153, 153));
        jButton3.setForeground(new java.awt.Color(0, 153, 153));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/My_Images/icons8-user-male-20.png"))); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, -1, -1));

        cari.setText("Cari Buku");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel3.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 380, -1, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 433, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.LINE_START);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setAutoscrolls(true);
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel5.setEnabled(false);
        jPanel5.setFocusable(false);

        jLabel9.setText("Nama :");

        jLabel10.setText("Pendidikan :");

        field_nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                field_namaActionPerformed(evt);
            }
        });

        jLabel11.setText("Alamat :");

        jTextFieldAlamat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAlamatActionPerformed(evt);
            }
        });

        jRadioButtonSMP1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupPddkn.add(jRadioButtonSMP1);
        jRadioButtonSMP1.setText("SMP");
        jRadioButtonSMP1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSMP1ActionPerformed(evt);
            }
        });

        jRadioButtonSMA1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupPddkn.add(jRadioButtonSMA1);
        jRadioButtonSMA1.setText("SMA/SMK Sederajat");
        jRadioButtonSMA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonSMAActionPerformed(evt);
            }
        });

        jRadioButtonMHS1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupPddkn.add(jRadioButtonMHS1);
        jRadioButtonMHS1.setText("Mahasiswa");
        jRadioButtonMHS1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMHSActionPerformed(evt);
            }
        });

        jRadioButtonKRJ1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupPddkn.add(jRadioButtonKRJ1);
        jRadioButtonKRJ1.setText("Bekerja");
        jRadioButtonKRJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonKRJActionPerformed(evt);
            }
        });

        jRadioButtonMU1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupPddkn.add(jRadioButtonMU1);
        jRadioButtonMU1.setText("Masyarakat Umum");
        jRadioButtonMU1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMUActionPerformed(evt);
            }
        });

        jButton4.setText("Submit");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setText("Jenis Kelamin :");

        jRadioButtonPerempuan1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupJK.add(jRadioButtonPerempuan1);
        jRadioButtonPerempuan1.setText("Perempuan");
        jRadioButtonPerempuan1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonPerempuanActionPerformed(evt);
            }
        });

        jRadioButtonLaki1.setBackground(new java.awt.Color(255, 255, 255));
        buttonGroupJK.add(jRadioButtonLaki1);
        jRadioButtonLaki1.setText("Laki-Laki");
        jRadioButtonLaki1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonLakiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAlamat1, javax.swing.GroupLayout.PREFERRED_SIZE, 289, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 112, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(field_nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jRadioButtonPerempuan1)
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonLaki1))
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonSMP1)
                                    .addComponent(jRadioButtonKRJ1))
                                .addGap(35, 35, 35)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jRadioButtonMU1)
                                    .addComponent(jRadioButtonSMA1))
                                .addGap(18, 18, 18)
                                .addComponent(jRadioButtonMHS1)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(113, 113, 113)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(field_nama1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonPerempuan1)
                    .addComponent(jRadioButtonLaki1))
                .addGap(18, 18, 18)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonSMP1)
                    .addComponent(jRadioButtonSMA1)
                    .addComponent(jRadioButtonMHS1))
                .addGap(27, 27, 27)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonKRJ1)
                    .addComponent(jRadioButtonMU1))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldAlamat1, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        NonAnggotaForm NonAnggotaFormFrame = new NonAnggotaForm();
        NonAnggotaFormFrame.setVisible(true);
        NonAnggotaFormFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
         AnggotaForm AnggotaFormFrame = new AnggotaForm();
        AnggotaFormFrame.setVisible(true);
        AnggotaFormFrame.setLocationRelativeTo(null);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jRadioButtonLakiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonLakiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonLakiActionPerformed

    private void jRadioButtonPerempuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonPerempuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonPerempuanActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

        String nama = field_nama1.getText();
        String jenisKelamin = jRadioButtonLaki1.isSelected() ? "Laki-laki" : "Perempuan";
        String pendidikan = "";
        if (jRadioButtonSMP1.isSelected()) {
            pendidikan = "SMP";
        } else if (jRadioButtonSMA1.isSelected()) {
            pendidikan = "SMA";
        } else if (jRadioButtonMHS1.isSelected()) {
            pendidikan = "Mahasiswa";
        } else if (jRadioButtonKRJ1.isSelected()) {
            pendidikan = "Bekerja";
        } else if (jRadioButtonMU1.isSelected()) {
            pendidikan = "Masyarakat";
        }
        String alamat = jTextFieldAlamat1.getText();

        String q = "INSERT INTO "
        + "datanonanggota(Nama, JenisKelamin, Pendidikan, Alamat) "
        + "VALUES ('"+nama+"','"+jenisKelamin+"','"+pendidikan+"','"+alamat+"')";

        Connection c = connect.getConnection();
        try {
            Statement s = c.createStatement();
            s.executeUpdate(q);
        } catch (Exception e) {
        }

        //check
        if (nama.trim().equals("") || jenisKelamin.trim().equals("") || pendidikan.trim().equals("") || alamat.trim().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Harap isi semua poin", "Empty Field", 0);
        }
        else
        JOptionPane.showMessageDialog(null,"Selamat Datang", "Data Masuk", 1);
         
       //remove after submit
         field_nama1.setText("");
         buttonGroupJK.clearSelection();
         buttonGroupPddkn.clearSelection();
         jTextFieldAlamat1.setText("");
        {
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jRadioButtonMUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMUActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMUActionPerformed

    private void jRadioButtonKRJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonKRJActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonKRJActionPerformed

    private void jRadioButtonMHSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMHSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonMHSActionPerformed

    private void jRadioButtonSMAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSMAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSMAActionPerformed

    private void jTextFieldAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAlamatActionPerformed

    private void field_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_field_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_field_namaActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        DataAnggota a = new DataAnggota();
        a.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jRadioButtonSMP1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonSMP1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButtonSMP1ActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
      CariBuku CariBukuFormFrame = new CariBuku();
        CariBukuFormFrame.setVisible(true);
        CariBukuFormFrame.setLocationRelativeTo(null);
        this.dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_cariActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NonAnggotaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NonAnggotaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NonAnggotaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NonAnggotaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NonAnggotaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupJK;
    private javax.swing.ButtonGroup buttonGroupPddkn;
    private javax.swing.JButton cari;
    private javax.swing.JTextField field_nama1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButtonKRJ1;
    private javax.swing.JRadioButton jRadioButtonLaki1;
    private javax.swing.JRadioButton jRadioButtonMHS1;
    private javax.swing.JRadioButton jRadioButtonMU1;
    private javax.swing.JRadioButton jRadioButtonPerempuan1;
    private javax.swing.JRadioButton jRadioButtonSMA1;
    private javax.swing.JRadioButton jRadioButtonSMP1;
    private javax.swing.JTextField jTextFieldAlamat1;
    // End of variables declaration//GEN-END:variables
}
